import pathlib

# GENERAL
COMPANY_NAME = 'ur'
ROBOT_NAME = 'gary'

# DOCKER
DOCKER_REPOSITORY = 'unlimitedrobotics'

CONTAINER_NAME_TEMPLATE = (
    '{repo}.{component}'
)

# GENERIC
FOLDER_SRC = 'src'
FOLDER_BUILD = 'build'
FOLDER_CONFIG = 'config'
FOLDER_COMMANDS = 'commands'
FOLDER_ROS_PKGS = 'ros_pkgs'
FOLDER_COMPONENTS = 'components'
FOLDER_GENERIC_PERSISTENT_DATA = 'generic_persistent_data'
FOLDER_COMPONENT_STATIC_DATA = 'component_static_data'
FOLDER_COMPONENT_PERSISTENT_DATA = 'component_persistent_data'

# LOCAL
DEV_ENV_PATH = pathlib.Path(__file__).resolve().parent.parent
LOCAL_SRC_PATH = DEV_ENV_PATH / FOLDER_SRC
FILE_ROS_DOMAINS_PATH = DEV_ENV_PATH / 'users_ros_domains.yaml'
FILE_ROBOTS_PATH = DEV_ENV_PATH / 'robots.yaml'

# GLOBAL
GLOBAL_BASE_PATH = pathlib.Path('/opt') / COMPANY_NAME / ROBOT_NAME
GLOBAL_CONFIG_PATH = GLOBAL_BASE_PATH / FOLDER_CONFIG

# ROBOT (INSIDE CONTAINER)
ROBOT_BASE_PATH = pathlib.Path('/robot')
ROBOT_COMMANDS_PATH = ROBOT_BASE_PATH / FOLDER_COMMANDS
ROBOT_GENERIC_PERSISTENT_DATA_PATH = ROBOT_BASE_PATH / FOLDER_GENERIC_PERSISTENT_DATA
ROBOT_COMPONENT_STATIC_DATA_PATH = ROBOT_BASE_PATH / FOLDER_COMPONENT_STATIC_DATA
ROBOT_COMPONENT_PERSISTENT_DATA_PATH = ROBOT_BASE_PATH / FOLDER_COMPONENT_PERSISTENT_DATA
ROBOT_CONFIG_PATH = ROBOT_BASE_PATH / FOLDER_CONFIG
ROBOT_BUILD_PATH = ROBOT_BASE_PATH / FOLDER_BUILD
ROBOT_SRC_PATH = ROBOT_BASE_PATH / FOLDER_SRC
ROBOT_ROS_PKGS_PATH = ROBOT_SRC_PATH / FOLDER_ROS_PKGS


# REMOTE HOST 
REMOTE_HOST_WORKSPACES_FOLDER_NAME = 'dev_workspaces'
