#!/usr/bin/env python3

import sys
from robotdevenv.components_tools import create_component_from_template

def main():
    # Check if exactly one argument is provided
    if len(sys.argv) != 3:
        print("Error: You must provide exactly two arguments with the new component name and the new group name")
        print("Usage: python3 new_components_group <group_name> <component_name>")
        sys.exit(1)

    # Get the new component name
    new_group_name = sys.argv[1]
    new_component_name = sys.argv[2]

    create_component_from_template(new_group_name, new_component_name)
    print(f"Component {new_component_name} successfully created in src/{new_group_name}")

if __name__ == "__main__":
    main()
